# Generated by Django 4.1.5 on 2023-01-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0002_alter_catergory_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catergory',
            name='parent',
        ),
    ]
