# Generated by Django 4.1.5 on 2023-01-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0005_alter_catergory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='catergorys',
        ),
    ]
