# Generated by Django 4.1.5 on 2023-01-03 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0006_remove_item_catergorys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout_catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styte', models.CharField(max_length=250, unique=True)),
                ('groud', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='layout',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='catergory',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload/catergory/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='catergory',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='layout',
            name='parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layout',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='priority',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='page',
            name='styte',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Layout_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload/layout_img/%Y/%m')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_demo_grapql.layout')),
            ],
        ),
        migrations.AddField(
            model_name='layout',
            name='catergory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_demo_grapql.layout_catergory'),
        ),
    ]
