# Generated by Django 4.1.5 on 2023-01-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0010_rename_img_layout_img_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='app_demo_grapql/static/upload/user/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='item',
            name='avatar',
            field=models.ImageField(upload_to='app_demo_grapql/static/upload/user/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='layout_img',
            name='avatar',
            field=models.ImageField(upload_to='app_demo_grapql/static/upload/user/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='avatar',
            field=models.ImageField(upload_to='app_demo_grapql/static/upload/user/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='app_demo_grapql/static/upload/user/%Y/%m'),
        ),
    ]
