# Generated by Django 4.1.5 on 2023-01-03 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0011_alter_catergory_avatar_alter_item_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dest',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='layout',
            name='dest',
            field=ckeditor.fields.RichTextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layout_img',
            name='dest',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
