# Generated by Django 4.1.5 on 2023-01-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0014_alter_catergory_avatar_alter_item_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prite_promotion',
            field=models.CharField(default=models.CharField(max_length=250), max_length=250),
        ),
    ]
