# Generated by Django 4.1.5 on 2023-01-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='avatar',
            field=models.ImageField(null=True, upload_to='upload/catergory/%Y/%m'),
        ),
    ]
