# Generated by Django 4.1.5 on 2023-01-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0003_remove_catergory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='catergory',
            name='parent',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
