# Generated by Django 4.1.5 on 2023-01-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0004_catergory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='parent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
