# Generated by Django 4.1.5 on 2023-01-03 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0007_layout_catergory_layout_name_alter_catergory_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_demo_grapql.page'),
            preserve_default=False,
        ),
    ]
