# Generated by Django 4.1.5 on 2023-01-03 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0008_layout_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout_img',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='layout_img',
            name='dest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layout_img',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='layout_img',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='layout_img',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='layout',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_demo_grapql.page'),
        ),
    ]
