# Generated by Django 4.1.5 on 2023-01-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0009_layout_img_active_layout_img_dest_layout_img_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout_img',
            old_name='img',
            new_name='avatar',
        ),
    ]
