# Generated by Django 4.1.5 on 2023-01-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0012_alter_item_dest_alter_layout_dest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload/Catergory/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='item',
            name='avatar',
            field=models.ImageField(upload_to='upload/Item/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='layout_img',
            name='avatar',
            field=models.ImageField(upload_to='upload/Layout_img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='avatar',
            field=models.ImageField(upload_to='upload/Menu/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='upload/user/%Y/%m'),
        ),
    ]
