# Generated by Django 4.1.5 on 2023-01-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0013_alter_catergory_avatar_alter_item_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/Catergory/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='item',
            name='avatar',
            field=models.ImageField(upload_to='static/upload/Item/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='layout_img',
            name='avatar',
            field=models.ImageField(upload_to='static/upload/Layout_img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='avatar',
            field=models.ImageField(upload_to='static/upload/Menu/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='static/upload/user/%Y/%m'),
        ),
    ]
