# Generated by Django 4.1.5 on 2023-01-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_grapql', '0015_item_prite_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prite_promotion',
            field=models.CharField(max_length=250),
        ),
    ]
